### PR TITLE
Adds Chakra UI To List and ListItem Components

### LINKED ISSUE #34: 16. List Design: As a user in the List component, I should be able to copy my list code, search for an item and be able to quickly add an item to my list.
## Summary
The List component will now be comprised of a copy list code feature, a search function, and an add item button along with the list items.

## Acceptance criteria
- [x] Header should be fixed and contain the List Luxe title.
- [x] When the user joins a new list or creates one and navigate directly to `/list`, the current token should be displayed along with a graphic to copy the token on click (Asset: `CkCopy`chakra icon)
- [x] The `Search` input field should include an `x` to clear the search filter. (Asset: `InputRightElement` with `CkClose` chakra icon)
- [x] `dialog` should be styled using a chakra `toast` component at the top of the page [tbd]

## Notes
Link to wireframe here: Android Small -3 https://www.figma.com/file/4oxU5wehZPNinZpr24UuLw/Chakra-UI-Figma-Kit-(Community)?type=design&node-id=2102-2110&t=ciT6mhpJqrDlx0bY-0 (we can clean this up to have all our assets in one place or also stored here in github).

- Toast chakra documentation: https://chakra-ui.com/docs/components/toast/usage

### LINKED ISSUE #35: 17. List Design: As a user, I should be able to see tabs with all of the items in each category and check a specific colored checkbox based on item urgency when an item is purchased.
## Summary
The List Items should now display based on the following categories: All, Overdue, Soon, Kind of Soon, Inactive.  Each item will include a dropdown accordion to display the `ListItemDetails.jsx` component as well as an option to delete the item. Each item will have a checkbox with a color designated by the category of urgency.

## Acceptance criteria
- [x] Tab asset should be added for each category.
- [x] The list items should be filtered and displayed only based on that category.
- [x] Each item will be displayed as an accordion button that includes the `ListItemDetails.jsx` (chakra asset: `AccordionButton`)
  - [x] A `x` icon (chakra asset: `InputRightElement` with `CkClose` chakra icon) will display in the accordion button and perform the `onClick` delete functionality
  - [x] Multiple items should be able to be expanded at once (`allowMultiple`)
- [x] Each item in the accordion button will have a checkbox color based on the urgency category (see wireframe styling)
- [x] Confirm alert that pops up when user deletes item should be styled using the chakra `AlertDialog` component instead of window.confirm

## Notes
Figma wireframe (should be updated): https://www.figma.com/file/4oxU5wehZPNinZpr24UuLw/Chakra-UI-Figma-Kit-(Community)?type=design&node-id=2102-2110&t=eJqiMz2U9GZKkHBQ-0
- Chakra Tabs documentation: https://chakra-ui.com/docs/components/tabs
- Chakra Accordion documentation: https://chakra-ui.com/docs/components/accordion/usage
- Chakra Textbox documentation: https://chakra-ui.com/docs/components/checkbox 
- Chakra AlertDialog documentation: https://chakra-ui.com/docs/components/alert-dialog

Color palette for checkboxes based on urgency will be set in the extended theme.

Screen Shot 2023-05-19 at 3 53 53 PM

### PR DESCRIPTION
**Pull request by Yaosaur**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description
This code changes the styling structure of all of the `List` and `ListItem` components by using chakra UI components.  It also adds a new component, `Dialog`, to replace the window.confirm dialog. This code also adds a new display for the user's current token and the ability to quickly copy the token.

Link to the design wireframe: https://www.figma.com/file/4oxU5wehZPNinZpr24UuLw/Chakra-UI-Figma-Kit-(Community)?type=design&node-id=2102-2110&t=ciT6mhpJqrDlx0bY-0 

## Related Issue

Closes #34 
Closes #35 

### Issue 16.
- [x] Header should be fixed and contain the List Luxe title.
- [x] When the user joins a new list or creates one and navigate directly to `/list`, the current token should be displayed along with a graphic to copy the token on click (Asset: `CkCopy`chakra icon)
- [x] The `Search` input field should include an `x` to clear the search filter. (Asset: `InputRightElement` with `CkClose` chakra icon)
- [x] `dialog` should be styled using a chakra `toast` component at the top of the page [tbd]

### Issue 17.
- [x] Tab asset should be added for each category.
- [x] The list items should be filtered and displayed only based on that category.
- [x] Each item will be displayed as an accordion button that includes the `ListItemDetails.jsx` (chakra asset: `AccordionButton`)
  - [x] A `x` icon (chakra asset: `InputRightElement` with `CkClose` chakra icon) will display in the accordion button and perform the `onClick` delete functionality
  - [x] Multiple items should be able to be expanded at once (`allowMultiple`)
- [x] Each item in the accordion button will have a checkbox color based on the urgency category (see wireframe styling)
- [x] Confirm alert that pops up when user deletes item should be styled using the chakra `AlertDialog` component instead of window.confirm

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
| ✓   | :sparkles: New feature     |
| ✓   | :hammer: Refactoring       |

### Before
Screen Shot 2023-05-26 at 9 36 53 PM

### After
image

## Testing Steps / QA Criteria

In your terminal, use `git checkout yj-ky-list-item-chakra` to create a new branch and switch over.
Use `git pull origin yj-ky-list-item-chakra` to bring the changes from remote to local.
`npm start` to start a local instance of our app

- Select the `Copy` icon next to the List token name and paste it somewhere to make sure the list is copied correctly onto the clipboard.
- When typing an item into the `Filter Items` input field, the list on whatever tab you're on should update along with all other tabs if you click through each category.
  - When you click on the `X` after your search, the lists should go back to the original items in each category and the input field should go back to the placeholder.
  - You should be able to hover over each Item in the list and click on it to drop down an accordion
    - The Item details should display below the item and you should be able to click the item again to close it
  - Clicking on the garbage can icon should open an Alert Dialog
  - Selecting `Cancel` will bring you back, selecting `Delete` will delete the item in firebase, remove it from the list, and a `Toast` should pop up if successful
- When the list is empty, the tabs and accordion should not display

### CODE REVIEW

**Comment by mentalcaries** [comment]
It's looking great!
My main concern:
- Font size is a bit hard to read on my end (not sure if this is addressed in another PR)

For future consideration: 
- a toast saying something like "token copied"

**Comment by jeremiahfallin** [comment]
After messing around with the code with Ticia I think we came up with with a nice solution for the Tabs overflowing. If you try the code in this gist then just the Tab titles should scroll and all of the details from the TabPanel should fit without overflowing:
https://gist.github.com/jeremiahfallin/132158b37eec2b71a2a8a9ac0709d36a

**Review by jeremiahfallin — COMMENTED** [review]
Looks a little bit off on really thin devices. May need to adjust some widths to get it all to fit, even if we need to have horizontal scroll.
image

**Review by ticiadev — CHANGES_REQUESTED** [review]
Everything is functional, and the tab highlighting looks great! I think the whole page is looking good besides the padding and scroll on smaller screens, but Jeremiah and I looked at it and he came up with a great solution that I think resolves those issues.

**Pull request merged**
